%% REFRESH
clear
close all
imaqreset

%% Parameters
videoNames = 'PlantYeastChoice_N1';    % root name for this experiment
num.fps = 3;    % acquisition frame rate
num.writeFPS = 3;   % frame rate of recorded video
  
num.vidLength = 5;  % desired video length in minues
num.sessionLength = 200;    % total recording length desired (in minutes)

% autogenerated parameters
num.framesPerVid = num.vidLength*num.fps*60;        % number of frames in each video
num.vids = ceil(num.sessionLength/num.vidLength);   % number of videos within the exp. session

% Directories: 
basePath = 'C:\Users\jeannelab\Documents\Evyn\DATA\';
dirName = strrep(datestr(datetime, 'mm-dd-yyyy'), '-', '.');
video_path = [basePath, dirName, '\'];
if ~isfolder(video_path); mkdir(video_path); end
searchPath = [basePath, dirName, '\*.csv'];         % path for temperature logging
% Make temp log dummy (for naming purposes)
fclose(fopen([video_path videoNames '_RampLog.csv'], 'w+'));

% image cropping parameters
full_ROI = [0 0 2048 2048];
partial_ROI = [493 693 1241 1222];
rectangular_ROI = [552 586 628 891]; %srectangular arena space

% Load in the camera / open preview
vid = videoinput('pointgrey', 1, 'F7_Raw8_2048x2048_Mode0');
src = getselectedsource(vid);

% camera parameters
src.Brightness = 11.127068;
src.Exposure  = 0;
src.FrameRate = num.fps;
src.Gain = 4.0;
src.Gamma = 1.5;
src.Shutter = 5;

vid.FramesPerTrigger = inf;
% vid.ROIPosition = rectangular_ROI;
%   vid.ROIPosition = full_ROI;
vid.ROIPosition = partial_ROI;

preview(vid)



%% Run experiment:
closepreview(vid)

% Get list of current logs
for n = 1:num.vids
    % pull the current temp reading from the chiller log
    tempLogStart(n,:) = logTempNow(searchPath);

    % Set video saving
    diskLogger = VideoWriter([video_path videoNames '_' num2str(n) '.avi'], 'Motion JPEG AVI');
    vid.LoggingMode = 'disk';   %'disk&memory'; 
    diskLogger.Quality = 65;
    diskLogger.FrameRate = num.writeFPS; 
    vid.DiskLogger = diskLogger;  

    start(vid)
    pause(num.vidLength*60) % pause for the duration of each video
    stop(vid)
    
    % pull the current temp reading from the chiller log
    tempLogEnd(n,:) = [n, logTempNow(searchPath)];
    
    fprintf(['\n' num2str(n) ' / ' num2str(num.vids)  '\n']) 
end

save([video_path videoNames 'dataMat'])
fprintf(['\n' 'Done' '\n']) 

%% 
% 6 min hold at upper temp
% 180 min ramp down to lower temp
% 6 min hold at lower temp

% order:
% start temp log
% start chiller ramp/soak protocol
% start matlab script

















